### ISSUE TITLE
($FILES) returns empty set on multipart/form-data submission, even though there is data in ($POST)

### ISSUE THREAD

**Issue by JeremyReimer** [taoeffect/dragonfly-newlisp#1]
Using: newlisp 10.2.8, Dragonfly 0.70
Environment: Linux 2.6.31-14-generic-pae Ubuntu with Apache 2.0

Code to generate the form:

    <form name='FileUpload' action='fileupload.cgi' method='POST' enctype='multipart/form-data'>
    <input type='file' name='uploaded_data'>
    <input type='submit' value='Upload' name='submit'>
    </form>

Code inside fileupload.cgi:

    <%
    ;; ($FILES) test
    (println "<P>Post: " ($POST))
    (println "<P>Files: " ($FILES))
    %>

Action: Clicked "Choose file" button, selected file, tried uploading image (JPEG), also tried with text file

Result: 

While there is file data shown in ($POST) there is nothing in ($FILES), it always comes back as the empty set "()" with length 0.  

Have tried on two different Ubuntu servers with Apache 2 with the same result.

**Comment by shoukei** [comment]
This fixed it for me!!!
dragonfly-newlisp/example-site/dragonfly-framework/lib/request.lsp

142 - (if (set 'val (regex-captcha (string var {="(.+?)"}) disp))
142 + (if (set 'val (regex-captcha (string "filename" {="(.+?)"}) disp))

I'm running
OSX10.10.5, newLISP v.10.7.1, —()o Dragonfly WEB FRAMEWORK VERSION 0.73

**Comment by shoukei** [comment]
Sorry, need to fix one more line for uploading multiple files to work and to work as documented.

dragonfly-newlisp/example-site/dragonfly-framework/lib/request.lsp

142 - (if (set 'val (regex-captcha (string var {="(.+?)"}) disp))
142 + (if (set 'val (regex-captcha (string "filename" {="(.+?)"}) disp))
143 - ($FILES var (list (list 'name val) (list 'data data) (list 'length (length data))))
143 + ($FILES val (list (list 'name var) (list 'data data) (list 'length (length data)))

Then, the following works as commented in the source.
;; use like this: (lookup 'data ($FILES "filename"))
;; Valid keys: 'data, 'name, 'length

The number of files uploaded can be obtained by  (length ($FILES)).
The name of each file can be obtained by (first (nth i ($FILES))) where i is the number starting from  0 for file1 and 1 for file2 ...

**Comment by taoeffect** [comment]
@shoukei you wanna send a PR with those fixes? 😄

**Comment by shoukei** [comment]
I sent a PR. Thank you!!

**Comment by taoeffect** [comment]
Thanks @shoukei! I should get around to bumping the version number (I've been away from this project for a while), but thankfully because there's no newlisp package manager it doesn't really matter much at the moment.
